baseURL = "https://www.aadhi.rocks"
languageCode = "en-us"
title = "Aadhi Manivannan"
theme = "noteworthy"

[params]
	email = "mailto:aadithyan.manivannan@gmail.com/"
	linkedin = "https://www.linkedin.com/in/aadhimanivannan/"
	github = "https://github.com/lyttlerock/"